# This rule is not used by the project probes itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to test.network.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: probes
    app.kubernetes.io/managed-by: kustomize
  name: webchecker-viewer-role
rules:
- apiGroups:
  - test.network.io
  resources:
  - webcheckers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.network.io
  resources:
  - webcheckers/status
  verbs:
  - get
